import {StyleProp} from 'react-native';
import {FlexAlignType, ViewProps, ViewStyle} from 'react-native';

export interface IBlock extends ViewProps {
  flex?: boolean;
  flexShrink?: boolean;
  flexGrow?: boolean;
  row?: boolean;
  column?: boolean;
  shadow?: boolean;
  backgroundColor?: string;
  space?: 'between' | 'around';
  padding?: number;
  margin?: number;
  alignStart?: boolean;
  alignCenter?: boolean;
  alignEnd?: boolean;
  wrap?: boolean;
  justifyCenter?: boolean;
  justifyEnd?: boolean;
  justifyStart?: boolean;
  paddingTop?: number;
  paddingBottom?: number;
  paddingLeft?: number;
  paddingRight?: number;
  marginBottom?: number;
  marginLeft?: number;
  marginRight?: number;
  marginTop?: number;
  paddingVertical?: number;
  paddingHorizontal?: number;
  marginVertical?: number;
  marginHorizontal?: number;
  radius?: number;
  height?: number | string;
  width?: number | string;
  square?: number;
  round?: number;
  borderWidth?: number;
  relative?: boolean;
  absolute?: boolean;
  top?: number;
  left?: number;
  right?: number;
  bottom?: number;
  borderColor?: string;
  overflow?: 'hidden' | 'scroll' | 'visible';
  alignSelf?: 'auto' | FlexAlignType;
  style?: StyleProp<ViewStyle>;
  shadowColor?: string;
  opacity?: number;
  elevation?: number;
}
